// import { skilltreeItem } from "src/types/data/viewsData"
// import {
//     SiJavascript, FaPython, FaHtml5, FaCss3Alt, SiMui,
//     FaGitAlt, FaDocker, RiReactjsFill, FaVuejs, IoLogoFigma, SiFlask, SiDjango, SiTensorflow, SiPytorch, SiVite,
//     GrMysql, BiLogoPostgresql, SiMongodb, DiRedis, IoLogoTableau, SiSonarqube, FaLine, SiFastapi, FaJenkins, SiAnaconda, SiTypescript, RiSupabaseFill, SiRender, IoLogoVercel, SiJsonwebtokens, DiDjango
// } from 'src/components/icons/skillIcons';
import {
    // front-end
    JavascriptPlainIcon,
    TypescriptPlainIcon,
    TailwindcssOriginalIcon,
    BootstrapPlainIcon,
    Html5OriginalIcon,
    Css3OriginalIcon,
    ReactOriginalIcon,
    VuejsOriginalIcon,
    MaterialuiOriginalIcon,
    ViteOriginalIcon,
    EslintPlainIcon,
    // back-end
    NodejsOriginalIcon,
    CsharpPlainIcon,
    DotNetPlainIcon,
    JavaOriginalIcon,
    PythonOriginalIcon,
    FlaskOriginalIcon,
    DjangoPlainIcon,
    FastapiOriginalIcon,
    PhpOriginalIcon,
    // Machine Learning
    TensorflowOriginalIcon,
    PytorchOriginalIcon,
    // DataBase
    PostgresqlPlainIcon,
    MongodbPlainIcon,
    MysqlOriginalIcon,
    RedisPlainIcon,
    // Tools & Platforms
    GitPlainIcon,
    DockerPlainIcon,
    AnacondaOriginalIcon,
    AzurePlainIcon,
    VercelOriginalIcon,
    SupabasePlainIcon,
    SonarqubeOriginalIcon,
    JenkinsOriginalIcon,
    // Design
    FigmaPlainIcon,
    PhotoshopPlainIcon,
    IllustratorPlainIcon,
} from 'src/components/icons/skillDevicon';
import type { projects } from "src/types/data/viewsData"

const { VITE_PUBLIC_URL: PUBLIC_URL } = import.meta.env;


const projecstData: Array<projects> = [
    {
        type: "business",
        title: "AI-Driven Usability & XAI Systems",
        role: "Student Researcher / Frontend Developer",
        img: {
            url: `${PUBLIC_URL}/imgs/businessproject_ai_driven_usability.png`,
            lable: "AI-Driven Usability & XAI Systems",
            source: "Image generated by Nano Banana AI",
        },
        tech: [
            { display: "cover", type: "frontend", lable: "React", icon: ReactOriginalIcon },
            { display: "cover", type: "backend", lable: "Python", icon: PythonOriginalIcon },
            { display: "cover", type: "devops", lable: "Azure", icon: AzurePlainIcon },
            { display: "cover", type: "ai", lable: "UXAgent" },
        ],
        summary: "Developed an AI-driven usability testing and chatbot system during a research internship at George Brown College, focusing on Explainable AI (XAI), Small Language Models (SLMs), and Retrieval-Aug",
        problem: 'Traditional usability testing methods are time-consuming, lack scalability, and provide limited insight into user behavior. Additionally, many AI-driven systems operate as “black boxes,” making it difficult to ensure transparency and trust in user-facing applications.',
        solution: 'Designed and implemented a modular AI system combining automated usability testing with SLM-based conversational agents. Leveraged virtual user personas to simulate interactions and generate actionable insights, while integrating a RAG-based chatbot with a no-code interface to enable transparent, customizable, and efficient user guidance.',
        impact: 'Enabled scalable and interpretable usability testing workflows, reduced friction in chatbot deployment within existing systems, and improved transparency of AI-generated responses. Contributed to building a user-centric framework that balances performance, explainability, and real-world implementation constraints.',
    },
    {
        type: "side",
        title: "Lost and Found Management System",
        role: "System Designer / Full-Stack Developer",
        img: {
            url: `${PUBLIC_URL}/imgs/sideproject_lost_and_found.png`,
            lable: "Lost and Found Management System",
            source: "Image generated by Nano Banana AI",
        },
        tech: [
            { display: "cover", type: "frontend", lable: "React", icon: ReactOriginalIcon },
            { display: "cover", type: "backend", lable: "Django", icon: DjangoPlainIcon },
            { display: "cover", type: "database", lable: "PostgreSQL", icon: PostgresqlPlainIcon },
            { display: "cover", type: "devops", lable: "Vercel", icon: VercelOriginalIcon },
            { display: "cover", type: "devops", lable: "Supabase", icon: SupabasePlainIcon },
            { display: "detail", type: "frontend", lable: "TypeScript", icon: TypescriptPlainIcon },
            { display: "detail", type: "frontend", lable: "MUI", icon: MaterialuiOriginalIcon },
            { display: "detail", type: "frontend", lable: "Vite", icon: ViteOriginalIcon },
            { display: "detail", type: "backend", lable: "Python", icon: PythonOriginalIcon },
            { display: "detail", type: "tool", lable: "Anaconda", icon: AnacondaOriginalIcon },
        ],
        link: [{
            type: 'repo',
            label: "Github",
            url: "https://github.com/jui-wen-chiang/lost-and-found-GBC-main"
        }],
        summary: "The system digitizes lost and found reporting and tracking to replace manual processes. It streamlines item verification through a centralized dashboard, significantly improving recovery efficiency and user convenience.",
        problem: 'In fragmented environments like college campuses, the process of reporting and recovering lost items is often disorganized, relying on scattered social media posts or physical bulletin boards. This lack of a centralized system leads to low recovery rates, redundant inquiries, and significant communication gaps between finders and owners.',
        solution: 'I developed a centralized Lost and Found Management System that streamlines the entire recovery lifecycle. The platform features categorized item logging, real-time status tracking, and a searchable database with filtered queries. By acting as a "knowledge bridge" between different stakeholders, the system ensures that information is synchronized and accessible to all users in real-time.',
        impact: 'The implementation of this system significantly reduced the time required to reunite lost items with their owners and minimized administrative overhead. It transformed a chaotic, manual process into a structured digital workflow, increasing transparency and providing users with a reliable, stress-free way to manage personal property recovery.',
    },
    {
        type: "business",
        title: "Real-Time Data Visualization Platform",
        role: "Full-Stack Developer",
        img: {
            url: `${PUBLIC_URL}/imgs/businessproject_dashboard.png`,
            lable: "Real-Time Data Visualization Platform",
            source: "Image generated by Nano Banana AI",
        },
        tech: [
            { display: "cover", type: "frontend", lable: "Vue", icon: VuejsOriginalIcon },
            { display: "cover", type: "backend", lable: "Python", icon: PythonOriginalIcon },
            { display: "cover", type: "database", lable: "PostgreSQL", icon: PostgresqlPlainIcon },
            { display: "cover", type: "devops", lable: "Docker", icon: DockerPlainIcon },
            { display: "cover", type: "database", lable: "Redis", icon: RedisPlainIcon },
            { display: "detail", type: "devops", lable: "Jenkins", icon: JenkinsOriginalIcon },
        ],
        summary: "A platform integrating heterogeneous data sources to provide real-time operational monitoring, enabling faster decision-making and improved production efficiency",
        problem: 'Legacy warehouse and logistics operations relied on siloed systems and manual Excel reporting, which became massive performance bottlenecks as data volumes scaled into the millions. These fragmented, formula-heavy spreadsheets were prone to crashes and introduced significant latency. This "data blindness" meant that equipment failures went undetected and resource imbalances such as overstocking or critical shortages were only identified after they had already disrupted the production line.',
        solution: 'I architected and developed a High-Performance Real-Time Data Visualization Platform using a microservices approach to eliminate data silos and establish a Single Source of Truth. The solution features a robust data pipeline capable of handling high-throughput ingestion, integrated with WebSockets for live data streaming. On the frontend, I built a dynamic, responsive dashboard using Vue.js that allows users to "drill down" from global operational overviews to specific SKU-level details, ensuring high-frequency updates remain fluid and actionable.',
        impact: "The platform transformed chaotic data into a strategic asset, drastically shortening the window between problem detection and informed action. By replacing manual workflows with a stabilized Dockerized infrastructure and automated CI/CD pipelines, the system improved organizational agility and resource allocation precision. Managers now have 100% visibility into equipment status and inventory turnover, effectively eliminating operational black holes and enhancing the company's competitive responsiveness in the market."
    },
    // {
    //     type: "business",
    //     title: "AI-Powered OCR Document Processing",
    //     subtitle: "Automating File Understanding",
    //     role: "AI Developer / Frontend Developer",
    //     img: {
    //         url: `${PUBLIC_URL}/imgs/businessproject_orc.png`,
    //         lable: "AI OCR Document Processing",
    //         source: "Free images from Pexels",
    //     },
    //     tech: [
    //         { display: "cover", type: "ai", lable: "PyTorch", icon: PytorchOriginalIcon },
    //         { display: "cover", type: "frontend", lable: "Vue", icon: VuejsOriginalIcon },
    //         { display: "cover", type: "backend", lable: "Python", icon: PythonOriginalIcon },
    //         { display: "cover", type: "backend", lable: "FastAPI", icon: FastapiOriginalIcon },
    //         { display: "cover", type: "devops", lable: "Docker", icon: DockerPlainIcon },
    //         { display: "detail", type: "database", lable: "MongoDB", icon: MongodbPlainIcon },
    //     ],
    //     summary: "An automated system using OCR and NLP to extract, classify, and transform unstructured text into structured data, significantly reducing manual workload.",
    //     problem: 'string',
    //     solution: 'string',
    //     impact: 'string',
    // },
    {
        type: "side",
        title: "AI Emotion Tracker: Deep Heart",
        subtitle: "AI-Based Sentiment Tracker:",
        role: "NLP Developer / Team Leader",
        img: {
            url: `${PUBLIC_URL}/imgs/sideproject_deepheart.png`,
            lable: "AI Emotion Tracker",
            source: "Image generated by Nano Banana AI",
        },
        tech: [
            { display: "cover", type: "ai", lable: "TensorFlow", icon: TensorflowOriginalIcon },
            { display: "cover", type: "backend", lable: "Python", icon: PythonOriginalIcon },
            { display: "cover", type: "database", lable: "MySQL", icon: MysqlOriginalIcon },
            { display: "detail", type: "database", lable: "Bert NLP" },
            { display: "detail", type: "database", lable: "Beautifulsoup" },
            { display: "detail", type: "database", lable: "Tableau" },

        ],
        summary: "An AI-driven application that analyzes journal entries to provide emotional trend statistics, helping users monitor mental well-being and identify the need for support.",
        problem: 'Traditional mood-tracking methods often rely on manual inputs and predefined emojis, which fail to capture the complexity and nuance of human emotions. Furthermore, long-form journal entries remain "dark data", users frequently struggle to identify patterns or emotional shifts buried within large volumes of text, making it difficult to objectively monitor mental well-being over time.',
        solution: 'This application leverages Large Language Models (LLMs) to transform natural language journal entries into actionable emotional insights. By integrating advanced sentiment analysis, the application automatically categorizes subtle emotional dimensions—such as anxiety, joy, or burnout—and visualizes these abstractions into intuitive trend statistics. This bridge between qualitative writing and quantitative data allows for a seamless, automated reflection process.',
        impact: 'The application empowers users with heightened self-awareness, enabling them to detect early signs of emotional decline or persistent stress patterns. By providing a data-driven perspective on mental health, Deep Heart facilitates proactive intervention, helping users determine when to seek professional support or adjust their lifestyle, ultimately fostering greater psychological resilience.',
    }
];


export { projecstData }