import {
    // front-end
    JavascriptPlainIcon,
    TypescriptPlainIcon,
    TailwindcssOriginalIcon,
    BootstrapPlainIcon,
    Html5OriginalIcon,
    Css3OriginalIcon,
    ReactOriginalIcon,
    VuejsOriginalIcon,
    MaterialuiOriginalIcon,
    ViteOriginalIcon,
    EslintPlainIcon,
    // back-end
    NodejsOriginalIcon,
    CsharpPlainIcon,
    DotNetPlainIcon,
    JavaOriginalIcon,
    PythonOriginalIcon,
    FlaskOriginalIcon,
    DjangoPlainIcon,
    FastapiOriginalIcon,
    PhpOriginalIcon,
    // Machine Learning
    TensorflowOriginalIcon,
    PytorchOriginalIcon,
    // DataBase
    PostgresqlPlainIcon,
    MongodbPlainIcon,
    MysqlOriginalIcon,
    RedisPlainIcon,
    // Tools & Platforms
    GitPlainIcon,
    DockerPlainIcon,
    AnacondaOriginalIcon,
    AzurePlainIcon,
    VercelOriginalIcon,
    SupabasePlainIcon,
    SonarqubeOriginalIcon,
    JenkinsOriginalIcon,
    // Design
    FigmaPlainIcon,
    PhotoshopPlainIcon,
    IllustratorPlainIcon,
} from 'src/components/icons/skillDevicon';
import type { projects } from "src/types/data/viewsData"

const { VITE_PUBLIC_URL: PUBLIC_URL } = import.meta.env;


const projecstData: Array<projects> = [
    {
        type: "business",
        title: "AI-Driven Usability & XAI Systems",
        role: "Student Researcher / Frontend Developer",
        img: {
            url: `${PUBLIC_URL}/imgs/projects/cover/businessproject_ai_driven_usability.png`,
            lable: "AI-Driven Usability & XAI Systems",
            source: "Image generated by Nano Banana AI",
        },
        tech: [
            { display: "cover", type: "frontend", lable: "React", icon: ReactOriginalIcon },
            { display: "cover", type: "backend", lable: "Python", icon: PythonOriginalIcon },
            { display: "cover", type: "devops", lable: "Azure", icon: AzurePlainIcon },
            { display: "cover", type: "ai", lable: "UXAgent" },
        ],
        detailImg: [{
            tag: "case",
            url: `${PUBLIC_URL}/imgs/projects/detail/businessproject_ai_driven_usability.png`,
            lable: "AI-Driven Usability & XAI Systems Case Study",
            source: "Image generated by GPT",
            bgColor: '#010316'
        }],
        summary: "Planned the RAG chatbot architecture & designed its UI, bridging XAI research and user-centred design for a CRM agency partner.",
        solution: "During my internship at George Brown College, I joined a research team collaborating with a full-service CRM agency to revolutionize website usability via AI-powered automated testing and Explainable AI (XAI). The core pain point: complex behavioural data was too difficult for designers to translate into actionable UI/UX improvements, creating a gap between data and user-forward design.",
        task: "My goal was to define the RAG chatbot architecture and design its UI/UX, delivering clear technical specs that enabled the team to move from research to development.",
        actions: [
            "Architecture Planning: Defined the system architecture for a RAG-based chatbot, outlining how LLMs would integrate with behavioural data for transparent (XAI) responses.",
            "User Flow & UI Design: Designed the chatbot interface and user flows, ensuring intuitive navigation for users exploring complex digital workflows.",
            "Preliminary Testing/System Validation: Executed the initial testing phase for the Agent framework, ensuring seamless integration with the agency’s platform.",
            "Literature Review/Framework Selection: Completed a comprehensive investigation of industry-leading usability tools"
        ],
        results: [
            "Deliverables: Implementation within existing codebases, RAG architecture specification, virtual persona documentation, and usability testing framework.",
            "Impact: Provided the foundational blueprint that enabled the team to move from research to development; bridged the gap between abstract AI concepts and concrete user interface design.",
            "Learning: Gained deep insight into XAI and RAG architecture, mastering how to design AI interfaces that remain transparent and user-centric before writing any code."
        ]
        // problem: 'Traditional usability testing methods are time-consuming, lack scalability, and provide limited insight into user behavior. Additionally, many AI-driven systems operate as “black boxes,” making it difficult to ensure transparency and trust in user-facing applications.',
        // solution: 'Designed and implemented a modular AI system combining automated usability testing with SLM-based conversational agents. Leveraged virtual user personas to simulate interactions and generate actionable insights, while integrating a RAG-based chatbot with a no-code interface to enable transparent, customizable, and efficient user guidance.',
        // impact: 'Enabled scalable and interpretable usability testing workflows, reduced friction in chatbot deployment within existing systems, and improved transparency of AI-generated responses. Contributed to building a user-centric framework that balances performance, explainability, and real-world implementation constraints.',
    },
    {
        type: "side",
        title: "Lost and Found Management System",
        role: "System Designer / Full-Stack Developer",
        img: {
            url: `${PUBLIC_URL}/imgs/projects/cover/sideproject_lost_and_found.png`,
            lable: "Lost and Found Management System",
            source: "Image generated by Nano Banana AI",
        },
        tech: [
            { display: "cover", type: "frontend", lable: "React", icon: ReactOriginalIcon },
            { display: "cover", type: "backend", lable: "Django", icon: DjangoPlainIcon },
            { display: "cover", type: "database", lable: "PostgreSQL", icon: PostgresqlPlainIcon },
            { display: "cover", type: "devops", lable: "Vercel", icon: VercelOriginalIcon },
            { display: "cover", type: "devops", lable: "Supabase", icon: SupabasePlainIcon },
            { display: "detail", type: "frontend", lable: "TypeScript", icon: TypescriptPlainIcon },
            { display: "detail", type: "frontend", lable: "MUI", icon: MaterialuiOriginalIcon },
            { display: "detail", type: "frontend", lable: "Vite", icon: ViteOriginalIcon },
            { display: "detail", type: "backend", lable: "Python", icon: PythonOriginalIcon },
            { display: "detail", type: "tool", lable: "Anaconda", icon: AnacondaOriginalIcon },
        ],
        link: [{
            type: 'repo',
            label: "Github",
            url: "https://github.com/jui-wen-chiang/lost-and-found-GBC-main"
        }],
        detailImg: [{
            tag: "case",
            url: `${PUBLIC_URL}/imgs/projects/detail/sideproject_lost_and_found.png`,
            lable: "Lost and Found Management System Case Study",
            source: "Image generated by GPT",
            bgColor: '#e3e9f6'
        }],
        summary: "A web-based Lost and Found Management System, centralizing manual item tracking into a single platform and reducing lost item recovery time.",
        solution: 'At George Brown College, a large and diverse student population led to lost items annually, managed through fragmented manual methods. This caused misplaced records, delayed responses, and low recovery rates for students trying to reclaim belongings.',
        task: "My goal was to design and build a centralized web application that streamlined lost item reporting, tracking, and claiming. My primary responsibility was system architecture design and backend development and delivering a fully functional system within one semester.",
        actions: [
            "Designed the system architecture, database schema, and user flow, then established the front-end/back-end project structure for seamless team handoff.",
            "Implemented database migration scripts and version-controlled schema changes to keep the team aligned",
            "Built the authentication infrastructure with user registration/login APIs, JWT/session management, and Role-Based Access Control (RBAC).",
            "Developed Search & Filtering APIs plus image upload handling with validation, compression, and security checks.",
            "Created Reporting & Analytics APIs with data aggregation.",
        ],
        results: [
            "Delivered a fully functional backend system with authentication, item management, search, and reporting APIs within one academic semester.",
            "The system supports role-based access for admins, students, and staff, ensuring secure and segmented data access.",
            "API response times are consistent thanks to DB indexing and caching optimizations.",
            "Provided a clean project structure and comprehensive technical documentation, enabling 4 team members to continue development with zero merge conflicts.",
            "The centralized platform replaced fragmented manual processes, significantly improving item recovery rate and reducing staff workload."
        ],
        // problem: 'In fragmented environments like college campuses, the process of reporting and recovering lost items is often disorganized, relying on scattered social media posts or physical bulletin boards. This lack of a centralized system leads to low recovery rates, redundant inquiries, and significant communication gaps between finders and owners.',
        // impact: 'The implementation of this system significantly reduced the time required to reunite lost items with their owners and minimized administrative overhead. It transformed a chaotic, manual process into a structured digital workflow, increasing transparency and providing users with a reliable, stress-free way to manage personal property recovery.',
    },
    {
        type: "business",
        title: "Real-Time Data Visualization Platform",
        role: "Full-Stack Developer",
        img: {
            url: `${PUBLIC_URL}/imgs/projects/cover/businessproject_dashboard.png`,
            lable: "Real-Time Data Visualization Platform",
            source: "Image generated by Nano Banana AI",
        },
        tech: [
            { display: "cover", type: "frontend", lable: "Vue", icon: VuejsOriginalIcon },
            { display: "cover", type: "backend", lable: "Python", icon: PythonOriginalIcon },
            { display: "cover", type: "database", lable: "PostgreSQL", icon: PostgresqlPlainIcon },
            { display: "cover", type: "devops", lable: "Docker", icon: DockerPlainIcon },
            { display: "cover", type: "database", lable: "Redis", icon: RedisPlainIcon },
            { display: "detail", type: "devops", lable: "Jenkins", icon: JenkinsOriginalIcon },
        ],
        detailImg: [{
            tag: "case",
            url: `${PUBLIC_URL}/imgs/projects/detail/businessproject_dashboard.png`,
            lable: "Real-Time Data Visualization Platform Case Study",
            source: "Image generated by GPT",
            bgColor: '#010316'
        }],
        summary: "A customizable dashboard solution designed to integrate cross-border logistics and operational data, providing enterprises with real-time strategic insights and performance tracking.",
        solution: 'In warehouse and tech operations, raw data was scattered across siloed systems or manually consolidated in Excel reports, which crashed under millions of daily records and introduced major latency. Without real-time monitoring, teams faced equipment failure blind spots (production stalls) and resource imbalances (overstocking/stockouts), severely undermining operational efficiency.',
        task: "My goal was to design and build the no-code analytics dashboard's frontend, unifying fragmented warehouse data into real-time visual insights. My primary responsibility was the configurable Vue.js UI and establishing a reusable component library to accelerate team development by 25%.",
        actions: [
            "Built a no-code analytics dashboard with Vue.js + TypeScript, enabling non-technical users to create custom visualizations without writing code.",
            "Engineered a configurable UI supporting 10+ chart types with dynamic style and data source customization for flexible reporting.",
            "Established a reusable Vue.js component library, accelerating feature development by 25% across the team.",
            "Standardized flow diagrams to streamline cross-team alignment, reducing development time by 30%.",
            "Developed a high-performance Python SQLAlchemy backend layer to enable real-time hardware data integration from warehouse equipment and inventory systems."
        ],
        results: [
            "Reduced user decision time by 70% by delivering real-time dashboards that surface equipment status and inventory levels instantly.",
            "Enabled real-time monitoring of millions of daily records, eliminating equipment failure blind spots and preventing production stalls.",
            "Achieved unified data consistency, eliminating Excel-based silos and reducing reporting latency from hours to seconds.",
            " Accelerated team velocity by 25% through the reusable component library and 30% faster alignment via standardized flow diagrams.",
            "Empowered managers to make higher-quality, on-demand decisions, optimizing resource allocation and improving warehouse agility by identifying bottlenecks in real time. "
        ],
        // problem: 'Legacy warehouse and logistics operations relied on siloed systems and manual Excel reporting, which became massive performance bottlenecks as data volumes scaled into the millions. These fragmented, formula-heavy spreadsheets were prone to crashes and introduced significant latency. This "data blindness" meant that equipment failures went undetected and resource imbalances such as overstocking or critical shortages were only identified after they had already disrupted the production line.',
        // impact: "The platform transformed chaotic data into a strategic asset, drastically shortening the window between problem detection and informed action. By replacing manual workflows with a stabilized Dockerized infrastructure and automated CI/CD pipelines, the system improved organizational agility and resource allocation precision. Managers now have 100% visibility into equipment status and inventory turnover, effectively eliminating operational black holes and enhancing the company's competitive responsiveness in the market."
    },
    // {
    //     type: "business",
    //     title: "AI-Powered OCR Document Processing",
    //     subtitle: "Automating File Understanding",
    //     role: "AI Developer / Frontend Developer",
    //     img: {
    //         url: `${PUBLIC_URL}/imgs/businessproject_orc.png`,
    //         lable: "AI OCR Document Processing",
    //         source: "Free images from Pexels",
    //     },
    //     tech: [
    //         { display: "cover", type: "ai", lable: "PyTorch", icon: PytorchOriginalIcon },
    //         { display: "cover", type: "frontend", lable: "Vue", icon: VuejsOriginalIcon },
    //         { display: "cover", type: "backend", lable: "Python", icon: PythonOriginalIcon },
    //         { display: "cover", type: "backend", lable: "FastAPI", icon: FastapiOriginalIcon },
    //         { display: "cover", type: "devops", lable: "Docker", icon: DockerPlainIcon },
    //         { display: "detail", type: "database", lable: "MongoDB", icon: MongodbPlainIcon },
    //     ],
    //     summary: "An automated system using OCR and NLP to extract, classify, and transform unstructured text into structured data, significantly reducing manual workload.",
    //     problem: 'string',
    //     solution: 'string',
    //     impact: 'string',
    // },
    {
        type: "side",
        title: "AI-Based Emotion Tracker",
        subtitle: "AI-Based Emotion Tracker",
        role: "NLP Developer / Team Leader",
        img: {
            url: `${PUBLIC_URL}/imgs/projects/cover/sideproject_deepheart.png`,
            lable: "AI-Based Emotion Tracker",
            source: "Image generated by Nano Banana AI",
        },
        tech: [
            { display: "cover", type: "ai", lable: "TensorFlow", icon: TensorflowOriginalIcon },
            { display: "cover", type: "backend", lable: "Python", icon: PythonOriginalIcon },
            { display: "cover", type: "database", lable: "MySQL", icon: MysqlOriginalIcon },
            { display: "detail", type: "database", lable: "Bert NLP" },
            { display: "detail", type: "database", lable: "Beautifulsoup" },
            { display: "detail", type: "database", lable: "Tableau" },
        ],
        detailImg: [{
            tag: "case",
            url: `${PUBLIC_URL}/imgs/projects/detail/sideproject_deepheart.png`,
            lable: "AI Emotion Tracker Case Study",
            source: "Image generated by GPT",
            bgColor: '#fef4f0'
        }],
        summary: "Built DeepHeart, an AI mental health platform using fine-tuned BERT to classify emotions in journals, transforming reflections into visual mood trends for users and therapists.",
        solution: 'Many people struggle to articulate or track emotions over time, and traditional emoji-based trackers miss emotional nuance, leaving therapists without objective data to guide therapy progress.',
        task: "My goal was to build the core BERT emotion detection engine and full-stack architecture, including fine-tuning the model, engineering the dataset, designing UI/UX, and integrating a LINE Bot for multi-platform access.",
        actions: [
            "Fine-tuned pre-trained BERT models for single-label emotion classification, optimizing hyperparameters and implementing evaluation metrics to boost accuracy beyond keyword-based trackers.",
            "Built a web crawler with BeautifulSoup to collect and label large-scale emotion datasets from public sharing platforms, enabling robust model training.",
            "Designed the complete user flow, visual layouts, and logo, ensuring a seamless, empathetic experience for users tracking their emotional journeys.",
        ],
        results: [
            "Delivered a fully functional AI emotion detection system with BERT-based classification that captures emotional intensity and tone shifts in full-text journal entries within three months.",
            "Enabled longitudinal mood tracking with visualized trend graphs, allowing users and therapists to compare pre/post-counselling emotional shifts for better clinical focus.",
            "Achieved multi-platform accessibility (responsive web, Android app, and LINE bot), reaching users through their preferred access points and increasing daily engagement.",
            "Received positive feedback from a psychologist who noted the tool effectively helps clients reflect and identify distress patterns early.",
            "Created a secure, private space for emotional reflection that empowers users to recognize, accept, and express emotions while providing therapists with data-driven insights."
        ]
        // problem: 'Traditional mood-tracking methods often rely on manual inputs and predefined emojis, which fail to capture the complexity and nuance of human emotions. Furthermore, long-form journal entries remain "dark data", users frequently struggle to identify patterns or emotional shifts buried within large volumes of text, making it difficult to objectively monitor mental well-being over time.',
        // impact: 'The application empowers users with heightened self-awareness, enabling them to detect early signs of emotional decline or persistent stress patterns. By providing a data-driven perspective on mental health, Deep Heart facilitates proactive intervention, helping users determine when to seek professional support or adjust their lifestyle, ultimately fostering greater psychological resilience.',
    }
];


export { projecstData }