// import { skilltreeItem } from "src/types/data/viewsData"
// import {
//     SiJavascript, FaPython, FaHtml5, FaCss3Alt, SiMui,
//     FaGitAlt, FaDocker, RiReactjsFill, FaVuejs, IoLogoFigma, SiFlask, SiDjango, SiTensorflow, SiPytorch, SiVite,
//     GrMysql, BiLogoPostgresql, SiMongodb, DiRedis, IoLogoTableau, SiSonarqube, FaLine, SiFastapi, FaJenkins, SiAnaconda, SiTypescript, RiSupabaseFill, SiRender, IoLogoVercel, SiJsonwebtokens, DiDjango
// } from 'src/components/icons/skillIcons';

const { VITE_PUBLIC_URL: PUBLIC_URL } = import.meta.env;

// const { PUBLIC_URL } = process.env;

const projectData = [
    {
        type: 'Side Project',
        title: 'Lost and Found Management System',
        // subtitle: "AI-Based Sentiment Tracker",
        image: `${PUBLIC_URL}/imgs/sideproject_lost_and_found.png`,
        imgsource: "Image generated by Nano Banana AI",
        // summary: 'This web-based Lost and Found system digitizes the reporting and tracking process, allowing users to easily search for items and upload photos online. By replacing manual procedures with a centralized admin dashboard, the system streamlines verification and significantly improves item recovery efficiency.',
        summary: 'The system digitizes lost and found reporting and tracking to replace manual processes. It streamlines item verification through a centralized dashboard, significantly improving recovery efficiency and user convenience.',
        // keyFeatures: [
        //     "AI-powered sentiment analysis.",
        //     "Diary input interface for emotional expression.",
        //     "Visual statistics of emotional trends."
        // ],
        // icons: [
        //     { lable: 'Vite', src: SiVite },
        //     { lable: 'React', src: RiReactjsFill },
        //     { lable: 'MUI', src: SiMui },
        //     { lable: 'TypeScript', src: SiTypescript },
        //     { lable: 'Django', src: DiDjango },
        //     { lable: 'Python', src: FaPython },
        //     { lable: 'PostgreSQL', src: BiLogoPostgresql },
        //     { lable: 'JWT - JSON Web Token', src: SiJsonwebtokens },
        //     { lable: 'Vercel', src: IoLogoVercel },
        //     { lable: 'Render Web Service', src: SiRender },
        //     { lable: 'Supabase', src: RiSupabaseFill },
        //     { lable: 'Miniconda', src: SiAnaconda },
        // ],
        details: {},
    },
    {
        type: 'Business Project',
        title: 'The Situation Dashboard',
        subtitle: "Real-Time Data Visualization Platform",
        image: `${PUBLIC_URL}/imgs/businessproject_dashboard.png`,
        imgsource: "Image generated by Nano Banana AI",
        summary: 'A platform integrating heterogeneous data sources to provide real-time operational monitoring, enabling faster decision-making and improved production efficiency',
        keyFeatures: [
            "Real-time data synchronization and visualization.",
            "Dashboard interface for intuitive monitoring.",
            "Enhanced decision-making through data integration."
        ],
        // icons: [
        //     { lable: 'VueJS', src: FaVuejs },
        //     { lable: 'Python', src: FaPython },
        //     { lable: 'PostgreSQL', src: BiLogoPostgresql },
        //     { lable: 'Redis', src: DiRedis },
        //     { lable: 'Docker', src: FaDocker },
        //     { lable: 'Jenkins', src: FaJenkins },
        //     { lable: 'I18n' },
        // ],
        details: {},
        techStack: ["python", "Vue"]
    },
    {
        type: 'Business Project',
        title: 'AI-Powered OCR Document Processing',
        subtitle: "Automating File Understanding",
        image: `${PUBLIC_URL}/imgs/businessproject_orc.jpg`,
        imgsource: "Free images from Pexels",
        summary: 'An automated system using OCR and NLP to extract, classify, and transform unstructured text into structured data, significantly reducing manual workload.',
        keyFeatures: [
            "OCR-powered text extraction from scanned files.",
            "NLP-based semantic understanding of text blocks.",
            "Automatic document classification and structuring."
        ],
        // icons: [
        //     { lable: 'PyTorch', src: SiPytorch },
        //     { lable: 'Python', src: FaPython },
        //     { lable: 'FastAPI', src: SiFastapi },
        //     { lable: 'VueJS', src: FaVuejs },
        //     { lable: 'MongoDB', src: SiMongodb },
        //     { lable: 'Docker', src: FaDocker },
        //     { lable: 'Bert NPL' },
        // ],
        details: {},
    },
    {
        type: 'Side Project',
        title: 'AI Emotion Tracker',
        // title: 'Emotion Journal App - Deepheart',
        subtitle: "AI-Based Sentiment Tracker",
        image: `${PUBLIC_URL}/imgs/sideproject_deepheart.png`,
        imgsource: "Image generated by Nano Banana AI",
        summary: 'An AI-driven application that analyzes journal entries to provide emotional trend statistics, helping users monitor mental well-being and identify the need for support.',
        keyFeatures: [
            "AI-powered sentiment analysis.",
            "Diary input interface for emotional expression.",
            "Visual statistics of emotional trends."
        ],
        // icons: [
        //     { lable: 'Tensorflow', src: SiTensorflow },
        //     { lable: 'MySQL', src: GrMysql },
        //     { lable: 'Python', src: FaPython },
        //     { lable: 'Tableau', src: IoLogoTableau },
        //     { lable: 'LineBot', src: FaLine },
        //     { lable: 'Bert NPL' },
        //     { lable: 'Beautifulsoup' },
        // ],
        details: {},
    }
];


export { projectData }